syntax:
- "mkdocs"
- "stellar"

cdn:
  # host: "https://github.elemecdn.com"
  host: "https://unpkg.com"
  # host: "https://gcore.jsdelivr.net/npm"

  package:
  - link: "host://lxgw-wenkai-screen-webfont@1.1.0/lxgwwenkaiscreen.css"

  - script: "host://jquery@3.6.3/dist/jquery.min.js"
  - script: "host://withinviewport@2.1.2/withinviewport.js"
  - script: "host://withinviewport@2.1.2/jquery.withinviewport.js"

  - script: "host://mermaid@9.4.0/dist/mermaid.js"

  - link: "host://@fancyapps/ui@5.0/dist/fancybox/fancybox.css"
  - script: "host://@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js"
    defer: true

  - script: "/js/img.js"
    defer: true

  - script: "/js/toc.js"
    defer: true

  - script: "/js/codeblock.js"
    defer: true

  - script: "/js/mathjax.js"
    defer: true
  - script: "host://mathjax@2.7.7/MathJax.js"
    defer: true